### ISSUE TITLE
entrypoint.sh script or Dockerfile for the pvcb-edit image?

### ISSUE THREAD

**Issue by kastl-ars** [clbx/kubectl-browse-pvc#20]
I found that I can use a different image for the newly created pod by using the `-i image` option.

However, it seems that other images are not working, either because there is no `bash` inside or because they are missing the `entrypoint.sh`.

I found the `pvcb-edit` image on [Docker Hub](https://hub.docker.com/r/clbx/pvcb-edit but found no Dockerfile for this image. I found Dockerfile and entrypoint.sh for the pvcb-editor image in this repository.

It would be nice to have these pieces available, to be able to use "our own" trusted image in security-constrained environments.

Thanks a lot in advance!

**Comment by clbx** [comment]
Hi, its in this repository: https://github.com/clbx/kubectl-browse-pvc/tree/main/Dockerfiles

**Comment by kastl-ars** [comment]
OK, thanks for the information.

**Comment by batagy** [comment]
Hi!

I'm also interested in this possibility, i.e. to run some other image in pvcb-edit pod.
I tested with with this command:
`kubectl browse-pvc -n namespace backup-pvc -i frolvlad/alpine-bash`
Since that image contains a bash inside.

I get "Pod failed to start", because of this error in pod/container log:
`/bin/bash: line 1: /entrypoint.sh: No such file or directory`

But if I check in the frolvlad/alpine-bash image, there is a /bin/bash.
What is wrong and how can I fix it?

**Comment by clbx** [comment]
@batagy it's complaining because the [entrypoint.sh](https://github.com/clbx/kubectl-browse-pvc/blob/main/entrypoint.sh) script doesn't exist in your container, putting that into your image will fix the issue you're having. The entrypoint script is needed so the pod terminates whenever the connection is terminate. It's not injected or anything, though that would be an interesting feature so more generic images can be used.

**Comment by clbx** [comment]
Using generic images is now possible as of 1.0.6

**Comment by batagy** [comment]
@clbx Sorry for late feedback!
I tested with version 1.0.7 and it works fantastic with other image!
Thanks for your implementation!
